dist: xenial
addons:
  apt_packages:
    - language-pack-fr
    - language-pack-fr-base
  chrome: stable
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/casperjs-1.1.4
services:
  - xvfb
env:
  global:
    - DISPLAY=:99.0
    - DISABLE_XDEBUG=1
    - DB_USER=root
    - DB_HOST=127.0.0.1
    - DB_PASSWORD=root
    - COMPOSIER_FULL_UPDATE=0
jobs:
  include:
    - name: "PHP 5.6"
      php: "5.6"
      addons:
        mariadb: 10.0
    - name: "PHP 7.0 MariaDB 10.0"
      php: "7.0"
      addons:
        mariadb: 10.0
    - name: "PHP 7.0 Composer full update"
      php: "7.0"
      env: COMPOSIER_FULL_UPDATE=1
    - name: "PHP 7.1 MariaDB 10.1"
      php: "7.1"
      addons:
        mariadb: 10.1
    - name: "PHP 7.1 Composer full update"
      php: "7.1"
      env: COMPOSIER_FULL_UPDATE=1
    - name: "PHP 7.2 MariaDB 10.2"
      php: "7.2"
      addons:
        mariadb: 10.2
    - name: "PHP 7.2 Composer full update"
      php: "7.2"
      env: COMPOSIER_FULL_UPDATE=1
    - name: "PHP 7.3 MariaDB 10.3"
      php: "7.3"
      addons:
        mariadb: 10.3
    - name: "PHP 7.3 Composer full update"
      php: "7.3"
      env: COMPOSIER_FULL_UPDATE=1
    - name: "PHP 7.4 MariaDB 10.4"
      php: "7.4"
      addons:
        mariadb: 10.4
    - name: "PHP 7.4 Composer full update"
      php: "7.4"
      env: COMPOSIER_FULL_UPDATE=1
    - name: "PHP 7.4 MariaDB 10.5"
      php: "7.4"
      addons:
        mariadb: 10.5
#    - name: "PHP nightly"
#      php: "nightly"
#      env: COMPOSIER_FULL_UPDATE=0
#    - name: "PHP nightly Composer full update"
#      php: "nightly"
#      env: COMPOSIER_FULL_UPDATE=1
#  allow_failures:
#    - php: nightly
before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer install --no-interaction --prefer-dist
  - if [ "$COMPOSIER_FULL_UPDATE" = "1" ]; then composer update --no-interaction --prefer-dist; fi
  - sh -c "mysql -u$DB_USER --password=$DB_PASSWORD -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS
    thelia;SET FOREIGN_KEY_CHECKS = 1;'; fi"
  - php Thelia thelia:install --db_host=$DB_HOST --db_password=$DB_PASSWORD --db_username=$DB_USER --db_name=thelia
  - php setup/faker.php -r 0
  - php Thelia module:refresh
  - php Thelia module:activate Colissimo
  - php Thelia module:activate Cheque
  - php Thelia module:activate HookTest
  - php Thelia module:activate VirtualProductDelivery
  - php Thelia admin:create --login_name thelia2 --password thelia2 --last_name thelia2 --first_name thelia2 --email thelia2@example.com
  - export PHANTOMJS_EXECUTABLE="$(which phantomjs)"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - php -S 127.0.0.1:8000 -t web/ >/dev/null 2>&1 &
  - sleep 3
  - bash tests/travis/install-casperjs.sh
  - export PATH=$PATH:$HOME/casperjs-1.1.4/bin
script: "./run-tests.sh"
