version: "3.7"

services:
  mariadb:
    image: mariadb:10.3
    container_name: docker-theliapi-mariadb
    working_dir: /application
    volumes:
      - .:/application
      - .docker/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "8086:3306"

  webserver:
    image: nginx:alpine
    container_name: docker-theliapi-webserver
    working_dir: /application
    volumes:
      - .:/application
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: .docker/php-fpm
    container_name: docker-theliapi-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - .docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - .docker/php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    environment:
      - PHP_IDE_CONFIG
      - XDEBUG_CONFIG
      - TEMPLATE_NAME

#  encore:
#    build:
#      context: ./templates/frontOffice/${TEMPLATE_NAME}
#      target: theliapi_encore
#    container_name: docker-theliapi-encore
#    working_dir: /application/templates/frontOffice/${TEMPLATE_NAME}
#    environment:
#      BROWSERSYNC_PROXY: http://localhost:8081
#    volumes:
#      - ./templates/frontOffice/${TEMPLATE_NAME}:/application/templates/frontOffice/${TEMPLATE_NAME}:delegated
#      - ./templates/frontOffice/${TEMPLATE_NAME}/node_modules:/application/templates/frontOffice/${TEMPLATE_NAME}/node_modules
#    ports:
#      - 8081:8081

  mailhog:
    image: mailhog/mailhog:latest
    container_name: docker-thelia-mailhog
    ports:
      - 8085:8025
