blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://discord.gg/YgwpYEE3y3
    about: We use GitHub issues only to discuss about Thelia bugs and new features. For this kind of questions about using Thelia or modules, please join our discord.
  - name: Documentation Issue
    url: https://github.com/thelia/docs/issues
    about: Thelia Documentation has its own dedicated repository.
